-- Upgrade SQL for adding Job Type Enum data for service jobs
UPDATE 
    SERVICE_JOB SJ_CHILD 
JOIN 
    SERVICE_JOB SJ_PARENT 
    ON SJ_CHILD.PARENT_JOB_NAME = SJ_PARENT.JOB_NAME  
SET 
    SJ_CHILD.JOB_TYPE_ENUM_ID = SJ_PARENT.JOB_TYPE_ENUM_ID
